name: FireworkWarsCore
version: '1.0-SNAPSHOT'
main: foundation.esoteric.fireworkwarscore.FireworkWarsCorePlugin
api-version: '1.21.3'
website: "https://github.com/EsotericFoundation/firework-wars-core-plugin"
loadbefore: [FireworkWarsPlugin, FireworkWarsLobbyPlugin]
load: "STARTUP"
